dist: xenial

os:
  - linux
  - osx
  - windows

language: node_js

node_js:
  - 10.5

services:
  - xvfb # Required for VSCode extension tests

script:
  - npm run compile
  - npm run lint
  - npm run test
