name: NPM Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false # don't cancel when one matrix job fails, so we can compare to the others
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "14.0.1"
          java-package: jdk
          architecture: x64

      - name: Install NPM dependencies
        run: npm install

      # https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
      - name: Run tests (headless)
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test --full-trace
