name: Test

on:
  push:
    branches: "master"
  pull_request:
    branches: [ "**" ]
  schedule:
    # At 09:00 on Monday and Wednesday
    - cron:  '0 9 * * 1,3'

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          # Prusti Assistant will automatically check and install the correct
          # toolchain version and components.
          toolchain: nightly-2020-09-30
          components: rustc-dev, llvm-tools-preview

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Run linter
        run: npm run lint

      - name: Run tests (headless)
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test --full-trace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
