name: NPM Tests

on:
  push:
    branches: "master"
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          java-package: jdk
          architecture: x64

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          # Prusti Assistant will automatically check and install the correct
          # toolchain version and components.
          toolchain: nightly-2020-09-30
          components: rustc-dev, llvm-tools-preview

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Run linter
        run: npm run lint

      - name: Run tests (headless)
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test --full-trace
