name: NPM Tests

on:
  push:
    branches: "master"
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          # TODO: choose automatically the toolchain version
          toolchain: nightly-2020-09-30
          components: rustc-dev, llvm-tools-preview

      - name: Install NPM dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      # https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
      - name: Run tests (headless)
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test --full-trace
