name: Test and publish

on:
  pull_request:
  schedule:
    # At 07:00 UTC on Monday
    - cron:  '0 7 * * 1'
  push:
    branches: "master"

jobs:
  # Test the extension on multiple OSs.
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          # On its first activation Prusti Assistant will automatically
          # install the correct toolchain version and components.
          toolchain: nightly-2020-09-30

      - name: Install NPM dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Package the extension
        run: npm run package

      - name: Run tests (headless)
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test --full-trace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect coverage
        run: npx nyc report --reporter=lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info

  # Publish the extension when we are on master and the version specified in
  # package.json is not the latest published version of the extension.
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Install NPM dependencies
        run: npm install
      
      - name: Obtain version information
        run: |
          LAST_PUBLISHED_VERSION="$(
            npx vsce show viper-admin.prusti-assistant --json \
              | jq '.versions[0].version' --raw-output
          )"
          CURRENT_VERSION="$(
            cat package.json | jq '.version' --raw-output
          )"
          echo "LAST_PUBLISHED_VERSION=$LAST_PUBLISHED_VERSION" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Publish the extension
        uses: lannonbr/vsce-action@master
        if: env.CURRENT_VERSION != env.LAST_PUBLISHED_VERSION
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Create a tag for the published version
        uses: richardsimko/update-tag@master
        if: env.CURRENT_VERSION != env.LAST_PUBLISHED_VERSION
        with:
          tag_name: v-${{ env.CURRENT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
