name: NPM Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check out VS Verification Toolbox # not on NPM yet
        uses: actions/checkout@v2
        with:
          repository: viperproject/vs-verification-toolbox
          path: .deps/vs-verification-toolbox

      - name: Link VS Verification Toolbox
        run: npm link .deps/vs-verification-toolbox

      - name: Install NPM dependencies
        run: npm install

      - name: Run tests
        run: npm test
